In [5]:
cd /Users/martin/Git/estates/src/data/silver

/Users/martin/Git/estates/src/data/silver

In [6]:
import pandas as pd
import os
import s3fs

In [21]:
import boto3
import json
from pathlib import Path

In [13]:
s3 = boto3.resource('s3')

content_object = s3.Object('estates-9036941568', 'data/bronze/20210508-211200_2910227036.json')
file_content = content_object.get()['Body'].read().decode('utf-8')
json_content = json.loads(file_content)

In [16]:
df = pd.DataFrame.from_dict(json_content, orient='index')
df.head()

,estate_title,estate_description_short,estate_description_long,estate_category_main_cb,estate_disposition,estate_rental_or_sell,estate_locality_district,estate_longitude,estate_latitude,estate_map_zoom,...,Provize,Zlevněno,Původní cena,Datum prohlídky,Výška stropu,Plocha bazénu,Datum prohlídky do,Anuita,Půdní vestavba,Stav
2910227036,Prodej pole 5 553 m²,"Pole 7 454 m² k prodeji Moravský Žižkov, okres...",Nabízíme k prodeji pozemek vedený jako orná pů...,3,20,1,74,16.944821,48.819428,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1920371292,Pronájem bytu 1+kk 55 m²,Byt 1+kk 55 m² k pronájmu Praha 7 - Holešovice...,"Sympatický byt v centru metropole, v lokalitě ...",1,2,2,5007,14.464863,50.096861,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412479580,Pronájem bytu 1+kk 59 m²,Byt 1+kk 59 m² k pronájmu Znojmo; 10 000 Kč za...,Nabízíme k pronájmu velmi pěkný byt o dispozic...,1,2,2,77,16.066184,48.846164,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018043740,Prodej bytu 2+kk 72 m²,Byt 2+kk 72 m² k prodeji Praha 5 - Stodůlky; 9...,Ve výhradním zastoupení nabízím krásný byt 2+k...,1,4,1,5005,14.319788,50.047387,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2484161884,Pronájem bytu 1+kk 56 m²,Byt 1+kk 56 m² k pronájmu Praha 10 - Strašnice...,Nabízím k pronájmu krásný prostorný byt 1+kk o...,1,2,2,5010,14.500568,50.065128,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
new_col_names = ['estate_id'] + df.columns.to_list()

In [18]:
df = df.reset_index()

In [19]:
df.columns = new_col_names

In [20]:
df.head()

,estate_id,estate_title,estate_description_short,estate_description_long,estate_category_main_cb,estate_disposition,estate_rental_or_sell,estate_locality_district,estate_longitude,estate_latitude,...,Provize,Zlevněno,Původní cena,Datum prohlídky,Výška stropu,Plocha bazénu,Datum prohlídky do,Anuita,Půdní vestavba,Stav
0,2910227036,Prodej pole 5 553 m²,"Pole 7 454 m² k prodeji Moravský Žižkov, okres...",Nabízíme k prodeji pozemek vedený jako orná pů...,3,20,1,74,16.944821,48.819428,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1920371292,Pronájem bytu 1+kk 55 m²,Byt 1+kk 55 m² k pronájmu Praha 7 - Holešovice...,"Sympatický byt v centru metropole, v lokalitě ...",1,2,2,5007,14.464863,50.096861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1412479580,Pronájem bytu 1+kk 59 m²,Byt 1+kk 59 m² k pronájmu Znojmo; 10 000 Kč za...,Nabízíme k pronájmu velmi pěkný byt o dispozic...,1,2,2,77,16.066184,48.846164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1018043740,Prodej bytu 2+kk 72 m²,Byt 2+kk 72 m² k prodeji Praha 5 - Stodůlky; 9...,Ve výhradním zastoupení nabízím krásný byt 2+k...,1,4,1,5005,14.319788,50.047387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2484161884,Pronájem bytu 1+kk 56 m²,Byt 1+kk 56 m² k pronájmu Praha 10 - Strašnice...,Nabízím k pronájmu krásný prostorný byt 1+kk o...,1,2,2,5010,14.500568,50.065128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
file_name = Path('data/bronze/20210508-211200_2910227036.json').stem
file_path = f's3://estates-9036941568/data/silver/{file_name}.csv'

In [30]:
file_path

's3://estates-9036941568/data/silver/20210508-211200_2910227036.csv'

In [33]:
df.to_csv(file_path, index=False)

In [34]:
pd.read_csv(file_path).head()

,estate_id,estate_title,estate_description_short,estate_description_long,estate_category_main_cb,estate_disposition,estate_rental_or_sell,estate_locality_district,estate_longitude,estate_latitude,...,Provize,Zlevněno,Původní cena,Datum prohlídky,Výška stropu,Plocha bazénu,Datum prohlídky do,Anuita,Půdní vestavba,Stav
0,2910227036,Prodej pole 5 553 m²,"Pole 7 454 m² k prodeji Moravský Žižkov, okres...",Nabízíme k prodeji pozemek vedený jako orná pů...,3,20,1,74,16.944821,48.819428,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1920371292,Pronájem bytu 1+kk 55 m²,Byt 1+kk 55 m² k pronájmu Praha 7 - Holešovice...,"Sympatický byt v centru metropole, v lokalitě ...",1,2,2,5007,14.464863,50.096861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1412479580,Pronájem bytu 1+kk 59 m²,Byt 1+kk 59 m² k pronájmu Znojmo; 10 000 Kč za...,Nabízíme k pronájmu velmi pěkný byt o dispozic...,1,2,2,77,16.066184,48.846164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1018043740,Prodej bytu 2+kk 72 m²,Byt 2+kk 72 m² k prodeji Praha 5 - Stodůlky; 9...,Ve výhradním zastoupení nabízím krásný byt 2+k...,1,4,1,5005,14.319788,50.047387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2484161884,Pronájem bytu 1+kk 56 m²,Byt 1+kk 56 m² k pronájmu Praha 10 - Strašnice...,Nabízím k pronájmu krásný prostorný byt 1+kk o...,1,2,2,5010,14.500568,50.065128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
bucket_name = 'estates'

In [39]:
'Found file %s in bucket %s' % (file_name, bucket_name)

'Found file 20210508-211200_2910227036 in bucket estates'